# This StatefulSet runs 1 pod with one Zero container and one Alpha container.
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName }}
        type: hStreamNode
        hsServiceName: {{ .Values.fullName }}
    spec:
      containers:
        - name: {{ .Values.containers.hs_adapter.name }}
          image:  {{ .Values.containers.hs_adapter.image }}
          ports:
            - containerPort: {{ .Values.service.zmqPort}}
          env:
            - name: "zmq.SocketUrl"
              value: "tcp://*:{{ .Values.service.zmqPort}}"
            - name: "dgraph.Host"
              value: "solenopsys-ds-dgraph.default.svc.cluster.local"
            - name: "dgraph.Port"
              value: "{{ .Values.service.httpPort }}"
